# Generated by Django 4.1.7 on 2023-06-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                ("short_disc", models.TextField(verbose_name="Краткое описание")),
                ("text", models.TextField(verbose_name="Описание проекта")),
                (
                    "attach",
                    models.FileField(
                        blank=True,
                        default="",
                        null=True,
                        upload_to="",
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "photo_link",
                    models.ImageField(
                        default="", upload_to="img/", verbose_name="Фото"
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
    ]
