# Generated by Django 4.1.7 on 2023-06-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="image",
            field=models.ImageField(
                blank=True, default="", upload_to="img/", verbose_name="Шкала"
            ),
        ),
    ]
